### ISSUE TITLE
libv8-5.1.281.59.1 depot_tools missing symlinks

### ISSUE THREAD

**Issue by marguerite** [cowboyd/libv8#220]
there're symlinks from vendor/depot_tools/support/chromite_wrapper to vendor/depot_tools/{cbuildbot,chrome_set_ver,cros,cros_sdk} in upstream's depot_tools

but our `.gem` doesn't have these symlinks.

so `gem specification --local --ruby libv8-5.1.281.59.1.gem > libv8-5.1.281.59.1.gemspec` will generate a gemspec whose filelist contains non-existent files.

marguerite

**Comment by ignisf** [comment]
Hmm, are you trying to repackage the gem as an RPM? Could you walk me through the process so I can easily replicate the issue here, @marguerite?

**Comment by marguerite** [comment]
@ignisf clever! I'm trying to update openSUSE's rubygem-libv8.

my workspace is here: https://build.opensuse.org/package/show/home:MargueriteSu:branches:devel:languages:ruby:extensions

you can enter rubygem-libv8-fail to see the raw build (enter and click the right fail indicator)

and the rubygem-libv8 is the build that solved this issue by `cp -r` chromite_wrapper to those files.

btw, is there any tarball with v8 embeded like before? openSUSE Build Service doesn't have network at build time, so I'll have to comment some `gclient sync` functions and upload v8 source to get it build.

**Comment by marguerite** [comment]
and in case you have no idea what %gem_unpack and %gem_build do:

https://build.opensuse.org/package/view_file/devel:languages:ruby/ruby-common/ruby.rpm-macros

they're documented here. just a few shell scripts.

basically, %gem_unpack does unpack `.gem` and `gem specification --ruby libv8-5.1.281.59.1.gem`.

while %gem_build does `gem build --verbose libv8-5.1.281.59.1.gemspec`.

**Comment by ignisf** [comment]
Thank you for the detailed explanation!

> btw, is there any tarball with v8 embeded like before

No, unfortunately the v8 build process has gotten very... Irregular (for political correctness)... To the point that we'd have to heavily patch it in order to eliminate the `gclient sync` call :(. I have considered it several times, but the frequent update schedule of the lib makes it impractical at this point.

I am going to have to take a look what exactly causes the missing files (though I have a suspicion that the "clever" decision to self-update `depot-tools` upon calling `gclient sync` causes it). Will update when I have more info.

In the meantime (though I imagine it's bad to have a special treatment for a specific gem), may I suggest that you try to build a platform specific version of the gem first and then run this platform specific version through said repackaging scripts instead of fetching the multiplatform version from rubygems?

One would fetch the source from this repo at the specific version and run

```
bundle install
bundle exec rake binary
```

A platform-specific gem containing just a binary statically linked v8 will be produced in the `pkg/` subdirectory.

Also, please do not release the 5.1.281.59 version as it is affected by https://github.com/cowboyd/libv8/issues/219. An update is imminent.

**Comment by ignisf** [comment]
For future reference, the correct link to the workspace is https://build.opensuse.org/package/show/home:MargueriteSu:branches:devel:languages:ruby:extensions

**Comment by ignisf** [comment]
@marguerite, is your issue still present? There have been a few releases since you opened it.
